// user results
export const FETCH_USER_RESULTS_REQUEST = 'FETCH_USER_RESULTS_REQUEST';
export const FETCH_USER_RESULTS_SUCCESS = 'FETCH_USER_RESULTS_SUCCESS';
export const FETCH_USER_RESULTS_FAILURE = 'FETCH_USER_RESULTS_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const FETCH_TRINER_RESULTS_REQUEST = 'FETCH_TRINER_RESULTS_REQUEST';
export const FETCH_TRINER_RESULTS_SUCCESS = 'FETCH_TRINER_RESULTS_SUCCESS';
export const FETCH_TRINER_RESULTS_FAILURE = 'FETCH_TRINER_RESULTS_FAILURE';
export const FETCH_ALL_TRAINERS = 'FETCH_ALL_TRAINERS';
export const ADD_SESSION_SUCCESS = 'ADD_SESSION_SUCCESS';
export const ADD_SESSION_FAIL = 'ADD_SESSION_FAIL';
export const FETCH_PARTICIPANT_BEHAVIORAL = 'FETCH_PARTICIPANT_BEHAVIORAL';
export const FETCH_SURVEY_BEHAVIORAL = 'FETCH_SURVEY_BEHAVIORAL';
export const FETCH_TRAINER_BEHAVIORAL = 'FETCH_TRAINER_BEHAVIORAL';
export const FETCH_LOCAL_LEADS = 'FETCH_LOCAL_LEADS';
export const CHECK_UNIQUE_EMAIL_UNIQUE = 'CHECK_UNIQUE_EMAIL_UNIQUE';
export const CHECK_UNIQUE_EMAIL_UNUNIQUE = 'CHECK_UNIQUE_EMAIL_UNUNIQUE';
export const FETCH_STATS = 'FETCH_STATS';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_UNAUTHENTICATED = 'USER_UNAUTHENTICATED';
export const FETCH_TRAINERS_SESSIONS = 'FETCH_TRAINERS_SESSIONS';
export const FETCH_LOCAL_LEAD_SESSIONS = 'FETCH_LOCAL_LEAD_SESSIONS';
export const FETCH_ALL_SESSIONS = 'FETCH_ALL_SESSIONS';
export const FETCH_SESSION_DETAILS = 'FETCH_SESSION_DETAILS';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const EDIT_SESSION_SUCCESS = 'EDIT_SESSION_SUCCESS';
export const UPDATE_EMAILS_SUCCESS = 'UPDATE_EMAILS_SUCCESS';
export const ADD_TRAINER_TO_GROUP_SUCCESS = 'ADD_TRAINER_TO_GROUP_SUCCESS';
export const ADD_TRAINER_TO_GROUP_FAIL = 'ADD_TRAINER_TO_GROUP_FAIL';
export const RESET_GROUPS_STATE = 'RESET_GROUPS_STATE';
export const RESET_UNIQUE_EMAIL = 'RESET_UNIQUE_EMAIL';
export const CHECK_UNIQUE_EMAIL_ERROR = 'CHECK_UNIQUE_EMAIL_ERROR';
export const FETCH_OVERALL_TRAINER_FEEDBACK = 'FETCH_OVERALL_TRAINER_FEEDBACK';
export const UPDATE_VIEW_LEVEL = 'UPDATE_VIEW_LEVEL';
export const FETCH_LOCAL_LEAD_TRAINERS_GROUP =
  'FETCH_LOCAL_LEAD_TRAINERS_GROUP';
export const SEND_SURVEY_EMAIL_SUCCESS = 'SEND_SURVEY_EMAIL_SUCCESS';
export const PARTICIPANT_FEEDBACK_SUCCESS = 'PARTICIPANT_FEEDBACK_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = '  CHANGE_PASSWORD_FAIL';

export const FETCH_PRTICIPENT_SESSIONS_REQUEST =
  'FETCH_PRTICIPENT_SESSIONS_REQUEST';
export const FETCH_PRTICIPENT_SESSIONS_SUCCESS =
  'FETCH_PRTICIPENT_SESSIONS_SUCCESS';
export const FETCH_PRTICIPENT_SESSIONS_FAILURE =
  'FETCH_PRTICIPENT_SESSIONS_FAILURE';
export const LOGOUT = 'LOGOUT';

export const EXPORT_DATA_SUCCESS = 'EXPORT_DATA_SUCCESS';
export const GET_PARTICIPANTS_DEMOGRAPHIC_SUCCESS =
  'GET_PARTICIPANTS_DEMOGRAPHIC_SUCCESS';
export const GET_PARTICIPANT_BY_PIN_SUCCESS = 'GET_PARTICIPANT_BY_PIN_SUCCESS';
export const FETCH_SESSIONS_PER_REGIONS = 'FETCH_SESSIONS_PER_REGIONS';

export const FETCH_SURVEY_DATA = 'FETCH_SURVEY_DATA';

export const SURVEY_PIN_EXIST_FAIL = 'SURVEY_PIN_EXIST_FAIL';
export const SURVEY_PIN_SUCCESS = 'SURVEY_PIN_SUCCESS';
export const SURVEY_SUBMISSION_SUCCESS = 'SURVEY_SUBMISSION_SUCCESS';
export const SURVEY_SUBMISSION_FAIL = 'SURVEY_SUBMISSION_FAIL';
export const GET_SESSION_DETAILS_BY_SHORT_ID =
  'GET_SESSION_DETAILS_BY_SHORT_ID';
export const CONFIRM_REGISTRATION_ERROR = 'CONFIRM_REGISTRATION_ERROR';
export const CONFIRM_REGISTRATION_SUCCESS = 'CONFIRM_REGISTRATION_SUCCESS';
export const GET_PARTICIPANT_BY_PIN_FAIL = 'GET_PARTICIPANT_BY_PIN_FAIL';
