export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const FETCH_TRINER_RESULTS_REQUEST = 'FETCH_TRINER_RESULTS_REQUEST';
export const FETCH_TRINER_RESULTS_SUCCESS = 'FETCH_TRINER_RESULTS_SUCCESS';
export const FETCH_TRINER_RESULTS_FAILURE = 'FETCH_TRINER_RESULTS_FAILURE';
